services:
  - type: web
    name: agentic-scraper-ui
    env: static
    buildCommand: chmod +x ./build.sh && ./build.sh
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
